name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run local registry
      run: docker run -d -p 5000:5000 registry:2
    
    - name: Run image from registry
      run: docker pull riki2225/build_and_push
      
    - name: Build and push image
      uses: ./
      env:
        DOCKER_BUILDKIT: 1
      with:
        registry: localhost:5000
        repository: riki2225/build_and_push
        tags: Dockerfile

    - name: Run image from registry
      run: docker run localhost:5000/riki2225/build_and_push:Dockerfile
