name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout
      uses: actions/checkout@v2.3.2

    - name: Run local registry
      run: docker run -d -p 5000:5000 registry:2
    
    - name: Build and push image
      env:
        DOCKER_BUILDKIT: 1
      with:
        registry: localhost:5000
        tags: Dockerfile

    - name: Run image from registry
      run: docker run --publish 8000:5000 --detach --name bb Dockerfile

