name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    
    - name: Check out code
      uses: actions/checkout@v1
      
    - name: Build
      run: npm ci
    
    - name: Run local registry
      run: docker run -d -p 5000:5000 registry:2
    
    - name: Build and push image
      uses: ./
      env:
        DOCKER_BUILDKIT: 1
      with:
        registry: localhost:5000
        repository: temp/workflow
        tags: foo
        image: 'Dockerfile'
    - name: Run image from registry
      run: docker run localhost:5000/temp/workflow:foo
